# Generated by Django 5.0.2 on 2024-04-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("car_id", models.IntegerField()),
                ("date_bought", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
