# Generated by Django 5.0.2 on 2024-03-25 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="task",
        ),
    ]
