# Generated by Django 5.0.2 on 2024-03-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mydbformclass",
            name="profile_img",
            field=models.FileField(upload_to="upload/"),
        ),
    ]
