# Generated by Django 5.0.2 on 2024-03-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0004_alter_mydbformclass_profile_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mydbformclass",
            name="profile_img",
            field=models.FileField(upload_to="app1/static/upload/"),
        ),
    ]
