# Generated by Django 5.0.2 on 2024-05-15 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_transaction_withdraw_access"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="Withdraw_access",
            new_name="withdraw_access",
        ),
    ]
