# Generated by Django 5.0.2 on 2024-05-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userbankaccount",
            name="withdraw_access",
            field=models.BooleanField(default=True),
        ),
    ]
