# Generated by Django 5.0.2 on 2024-03-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="musicians",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.IntegerField()),
                (
                    "instrument_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("guitar", "Guitar"),
                            ("piano", "Piano"),
                            ("drums", "Drums"),
                            ("violin", "Violin"),
                            ("flute", "Flute"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
