# Generated by Django 5.0.2 on 2024-05-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="Withdraw_access",
            field=models.BooleanField(default=True),
        ),
    ]
