# Generated by Django 5.0.2 on 2024-03-23 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("musician", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="albums",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("album_name", models.CharField(max_length=20)),
                ("release_date", models.DateField()),
                (
                    "rating",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "musician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="musician.musicians",
                    ),
                ),
            ],
        ),
    ]
