# Generated by Django 5.0.2 on 2024-03-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("album", "0002_alter_albums_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="albums",
            name="rating",
            field=models.CharField(
                choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4"), ("5", "5")],
                default=True,
                max_length=50,
            ),
        ),
    ]
