# Generated by Django 5.0.2 on 2024-03-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_title", models.CharField(max_length=50)),
                ("task_description", models.TextField(blank=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("date_assigned", models.DateField()),
            ],
        ),
    ]
