# Generated by Django 5.0.2 on 2024-05-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.IntegerField(
                choices=[
                    (1, "Deposit"),
                    (2, "Withdrawal"),
                    (3, "Loan"),
                    (4, "Loan Paid"),
                    (5, "transfer"),
                ],
                null=True,
            ),
        ),
    ]
