# Generated by Django 5.0.2 on 2024-03-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyDBFormClass",
            fields=[
                ("ID", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=10)),
            ],
        ),
    ]
