# Generated by Django 5.0.2 on 2024-03-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mydbformclass",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mydbformclass",
            name="balance",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
