# Generated by Django 5.0.2 on 2024-03-19 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_mydbformclass_website_alter_mydbformclass_balance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mydbformclass",
            name="about",
        ),
        migrations.RemoveField(
            model_name="mydbformclass",
            name="balance",
        ),
        migrations.RemoveField(
            model_name="mydbformclass",
            name="date",
        ),
        migrations.RemoveField(
            model_name="mydbformclass",
            name="email",
        ),
        migrations.RemoveField(
            model_name="mydbformclass",
            name="hour_rate",
        ),
        migrations.RemoveField(
            model_name="mydbformclass",
            name="login",
        ),
        migrations.RemoveField(
            model_name="mydbformclass",
            name="profile_img",
        ),
        migrations.RemoveField(
            model_name="mydbformclass",
            name="website",
        ),
    ]
