# Generated by Django 5.0.2 on 2024-03-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_remove_mydbformclass_about_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mydbformclass",
            name="balance",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
