# Generated by Django 5.0.2 on 2024-03-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_mydbformclass_about_mydbformclass_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mydbformclass",
            name="about",
            field=models.TextField(max_length=50),
        ),
    ]
