# Generated by Django 5.0.2 on 2024-03-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0006_alter_mydbformclass_about"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mydbformclass",
            name="about",
        ),
        migrations.RemoveField(
            model_name="mydbformclass",
            name="login",
        ),
    ]
