# Generated by Django 5.0.2 on 2024-03-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0007_remove_mydbformclass_about_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mydbformclass",
            name="login",
            field=models.BooleanField(default=True),
        ),
    ]
