# Generated by Django 5.0.2 on 2024-03-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0008_mydbformclass_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mydbformclass",
            name="login",
            field=models.BooleanField(),
        ),
    ]
